version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Root@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "2005:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
